export const SUDOKU_NEW_GAME = 'SUDOKU_NEW_GAME';
export const SUDOKU_RESET_GAME = 'SUDOKU_RESET_GAME';
export const SUDOKU_SOLVE_GAME = 'SUDOKU_SOLVE_GAME';
export const SUDOKU_UNDO = 'SUDOKU_UNDO';
export const SUDOKU_REDO = 'SUDOKU_REDO';
export const SUDOKU_SQUARE_CHANGE = 'SUDOKU_SQUARE_CHANGE';