// General
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIMER = 'RESET_TIMER';

// Sudoku
export const SUDOKU_TOGGLE_DIFFICULTY_PANEL = 'SUDOKU_TOGGLE_DIFFICULTY_PANEL';
export const SUDOKU_START_GAME = 'SUDOKU_START_GAME';
export const SUDOKU_RESET_GAME = 'SUDOKU_RESET_GAME';
export const SUDOKU_SOLVE_GAME = 'SUDOKU_SOLVE_GAME';
export const SUDOKU_UNDO = 'SUDOKU_UNDO';
export const SUDOKU_REDO = 'SUDOKU_REDO';
export const SUDOKU_CLEAR_HISTORY = 'SUDOKU_CLEAR_HISTORY';
export const SUDOKU_SQUARE_CHANGE = 'SUDOKU_SQUARE_CHANGE';
export const SUDOKU_USE_HINT = 'SUDOKU_USE_HINT';
export const SUDOKU_HINTS = 3
